export const FETCH_STANDARD_UNITS_REQUEST = 'FETCH_STANDARD_UNITS_REQUEST';
export const FETCH_STANDARD_UNITS_SUCCESS = 'FETCH_STANDARD_UNITS_SUCCESS';
export const FETCH_STANDARD_UNITS_FAILURE = 'FETCH_STANDARD_UNITS_FAILURE';

export const CREATE_STANDARD_UNIT_REQUEST = 'CREATE_STANDARD_UNIT_REQUEST';
export const CREATE_STANDARD_UNIT_SUCCESS = 'CREATE_STANDARD_UNIT_SUCCESS';
export const CREATE_STANDARD_UNIT_FAILURE = 'CREATE_STANDARD_UNIT_FAILURE';

export const UPDATE_STANDARD_UNIT_REQUEST = 'UPDATE_STANDARD_UNIT_REQUEST';
export const UPDATE_STANDARD_UNIT_SUCCESS = 'UPDATE_STANDARD_UNIT_SUCCESS';
export const UPDATE_STANDARD_UNIT_FAILURE = 'UPDATE_STANDARD_UNIT_FAILURE';

export const DELETE_STANDARD_UNIT_REQUEST = 'DELETE_STANDARD_UNIT_REQUEST';
export const DELETE_STANDARD_UNIT_SUCCESS = 'DELETE_STANDARD_UNIT_SUCCESS';
export const DELETE_STANDARD_UNIT_FAILURE = 'DELETE_STANDARD_UNIT_FAILURE';
